import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const languages = [
  { code: 'fr', label: 'FR' },
  { code: 'en', label: 'EN' },
  { code: 'ar', label: 'AR' },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = typeof window !== 'undefined' ? (window.location.pathname.split('/')[1] || 'fr') : 'fr';

  if (typeof document !== 'undefined') {
    if (locale === 'ar') {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  }

  const handleLangChange = (lang: string) => {
    const path = window.location.pathname.split('/').slice(2).join('/');
    window.location.href = `/${lang}/${path}`;
  };

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="flex justify-end p-4 border-b">
          <div className="flex gap-2">
            {languages.map((lang) => (
              <button
                key={lang.code}
                className={`px-3 py-1 rounded border ${locale === lang.code ? 'bg-black text-white' : 'bg-white text-black'}`}
                onClick={() => handleLangChange(lang.code)}
              >
                {lang.label}
              </button>
            ))}
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
